no change     /uufs/chpc.utah.edu/common/home/u1437983/software/pkg/miniforge3/condabin/conda
no change     /uufs/chpc.utah.edu/common/home/u1437983/software/pkg/miniforge3/bin/conda
no change     /uufs/chpc.utah.edu/common/home/u1437983/software/pkg/miniforge3/bin/conda-env
no change     /uufs/chpc.utah.edu/common/home/u1437983/software/pkg/miniforge3/bin/activate
no change     /uufs/chpc.utah.edu/common/home/u1437983/software/pkg/miniforge3/bin/deactivate
no change     /uufs/chpc.utah.edu/common/home/u1437983/software/pkg/miniforge3/etc/profile.d/conda.sh
no change     /uufs/chpc.utah.edu/common/home/u1437983/software/pkg/miniforge3/etc/fish/conf.d/conda.fish
no change     /uufs/chpc.utah.edu/common/home/u1437983/software/pkg/miniforge3/shell/condabin/Conda.psm1
no change     /uufs/chpc.utah.edu/common/home/u1437983/software/pkg/miniforge3/shell/condabin/conda-hook.ps1
no change     /uufs/chpc.utah.edu/common/home/u1437983/software/pkg/miniforge3/lib/python3.12/site-packages/xontrib/conda.xsh
no change     /uufs/chpc.utah.edu/common/home/u1437983/software/pkg/miniforge3/etc/profile.d/conda.csh
no change     /uufs/chpc.utah.edu/common/home/u1437983/.bashrc
No action taken.
Using device: NVIDIA GeForce RTX 3090
Traceback (most recent call last):
  File "/uufs/chpc.utah.edu/common/home/u1437983/Documents/NDA_Projects/NeuroSymbolic_BCI-Motor-Decoding/train_GRU_RNN.py", line 163, in <module>
    main(epochs=args.epochs, model_path=args.model_path, log_dir=args.log_dir, objective=args.objective)
  File "/uufs/chpc.utah.edu/common/home/u1437983/Documents/NDA_Projects/NeuroSymbolic_BCI-Motor-Decoding/train_GRU_RNN.py", line 66, in main
    cur_pos, spike_data, cur_vel = get_data_BIOCAS(inputfile)
  File "/uufs/chpc.utah.edu/common/home/u1437983/Documents/NDA_Projects/NeuroSymbolic_BCI-Motor-Decoding/util.py", line 146, in get_data_BIOCAS
    data = h5py.File(inputfile,'r')
  File "/uufs/chpc.utah.edu/common/home/u1437983/software/pkg/miniforge3/envs/Neurosymbolic/lib/python3.9/site-packages/h5py/_hl/files.py", line 562, in __init__
    fid = make_fid(name, mode, userblock_size, fapl, fcpl, swmr=swmr)
  File "/uufs/chpc.utah.edu/common/home/u1437983/software/pkg/miniforge3/envs/Neurosymbolic/lib/python3.9/site-packages/h5py/_hl/files.py", line 235, in make_fid
    fid = h5f.open(name, flags, fapl=fapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 102, in h5py.h5f.open
FileNotFoundError: [Errno 2] Unable to synchronously open file (unable to open file: name = 'Dataset/NHP Reaching Sensorimotor Ephys/indy_20160407_02.mat', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)
